apiVersion: gravitycloud.ai/v1alpha1
kind: GravityDeployment
metadata:
  name: mono-repo-js
spec:
  branch:
    - name: main
      approval: manual
    - name: development
      approval: automatic
    - name: feat-.*
      approval: automatic
  aws:
    repository:
      - name: mono-repo-js-east
        regions:
          - us-east-1
        branch: main
        valueFile:
          source: git
      - name: mono-repo-js-east
        regions:
          - us-east-1
        branch: development
        valueFile:
          source: git
      - name: mono-repo-js-east
        regions:
          - us-east-1
        branch: feat-.*
        valueFile:
          source: s3
          bucket: gravity-app-prod-values/feature-.*