{{- range $key, $value := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.name | default "default-name" }}-{{ $key | lower }}-secret
type: Opaque
data:
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}