name: Deploy
on:
  push:
    branches:
      - main

jobs:
  buildAndDeploy:
    name: Build and Deploy
    runs-on: self-hosted
    steps:
      - name: Echo Example Step
        run: echo "Hello World"
