name: Deploy
on:
  push:
    branches:
      - '*'         # Run on all branches
      - '**'        # Also include branches with slashes (e.g., feature/branch)

jobs:
  buildAndDeploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Echo Example Step
        run: echo "Hello World"
