name: nodejs-app-east
replicaCount: 1
image:
  repository: nodejs-app-east
  pullPolicy: IfNotPresent
  tag: 11199220926
service:
  type: ClusterIP
  port: 80
resources:
  requests:
    memory: 250Mi
    cpu: 250m
  limits:
    memory: 500Mi
    cpu: 500m
hpa:
  cpuUtilization:
    targetPercentage: 50
  maxReplicas: 2
  minReplicas: 1
