name: nodejs-app-east
replicaCount: 1
image:
  repository: nodejs-app-east
  pullPolicy: IfNotPresent
  tag: 54cc79fc6c450690cd8f3c06824b3883b3b74bbe
service:
  type: ClusterIP
  port: 80
resources:
  requests:
    memory: 250Mi
    cpu: 250m
  limits:
    memory: 500Mi
    cpu: 500m
secrets:
  NODE_ENV: production
  PORT: "80"
hpa:
  cpuUtilization:
    targetPercentage: 50
  maxReplicas: 2
  minReplicas: 1

redis:
  enabled: true
